const fs = require('fs');

const csv = fs.readFileSync('products_rows.csv', 'utf8');
const lines = csv.split('\n').slice(1); // Skip header
const products = [];

const categoryMap = {
  'Honey': 'honey',
  'Dry Fruit': 'dry-fruit',
  'Pure Arqiyat': 'pure-arqiyat',
  'Murabba Jat': 'murabba-jat',
  'Special Powders': 'special-powders',
  'Herbs': 'herbs',
  'Common Items': 'common-items',
  'Natural Items': 'natural-items',
  'Premium Items': 'premium-items'
};

const urduNames = {
  'Sidr Honey (Premium)': 'سدر شہد (پریمیم)',
  'Acacia Honey': 'اکیشیا شہد',
  'Wild Forest Honey': 'جنگلی جنگل شہد',
  'Clover Honey': 'کلوور شہد',
  'Manuka Style Honey': 'مینوکا اسٹائل شہد',
  'Eucalyptus Honey': 'یوکالیپٹس شہد',
  'Orange Blossom Honey': 'اورنج بلوسم شہد',
  'Buckwheat Honey': 'بک ویٹ شہد',
  'Neem Honey': 'نییم شہد',
  'Sunflower Honey': 'سن فلاور شہد',
  'Lavender Honey': 'لیوینڈر شہد',
  'Thyme Honey': 'تھائم شہد',
  'Black Seed Honey': 'بلیک سیڈ شہد',
  'Comb Honey': 'کومب شہد',
  'Ginger Infused Honey': 'جنگر انفیوزڈ شہد',
  'Mamra Almonds': 'ممرا بادام',
  'Walnut Kernels': 'والنٹ کرنلز',
  'Roasted Cashews': 'روسٹڈ کاجو',
  'Pistachios (Roasted)': 'پستے (روسٹڈ)',
  'Pine Nuts (Chilgoza)': 'پائن نٹس (چلغوزہ)',
  'Dried Figs (Anjeer)': 'ڈرائیڈ انجیر (انجیر)',
  'Green Raisins': 'گرین کشمش',
  'Black Raisins': 'بلیک کشمش',
  'Apricots (Dried)': 'خوبانی (ڈرائیڈ)',
  'Dates (Ajwa)': 'کھجور (عجوہ)',
  'Dates (Medjool)': 'کھجور (مجول)',
  'Hazelnuts': 'ہیزل نٹس',
  'Macadamia Nuts': 'میکادیمیا نٹس',
  'Pecans': 'پیکنز',
  'Brazil Nuts': 'برازیل نٹس',
  'Arq-e-Gulab': 'عرق گلاب',
  'Arq-e-Kasni': 'عرق کاسنی',
  'Arq-e-Mako': 'عرق ماکو',
  'Arq-e-Badiyan': 'عرق بادیان',
  'Arq-e-Nana': 'عرق نانا',
  'Arq-e-Ajwain': 'عرق اجوائن',
  'Arq-e-Chaharmaza': 'عرق چہار مضا',
  'Arq-e-Mundiyan': 'عرق مندیان',
  'Arq-e-Afsanteen': 'عرق افسطین',
  'Arq-e-Ushba': 'عرق اوشبا',
  'Arq-e-Nilofar': 'عرق نیلوفر',
  'Arq-e-Gaozaban': 'عرق گاؤزبان',
  'Arq-e-Shahtara': 'عرق شہترہ',
  'Arq-e-Bahar-e-Naranj': 'عرق بحر نارنج',
  'Arq-e-Murakkab': 'عرق مرکب',
  'Amla Murabba': 'املیہ مربہ',
  'Apple Murabba': 'سیب مربہ',
  'Carrot Murabba': 'گاجر مربہ',
  'Harar Murabba': 'ہرار مربہ',
  'Ginger Murabba': 'ادرک مربہ',
  'Bael Murabba': 'بیل مربہ',
  'Mango Murabba': 'آم مربہ',
  'Pineapple Murabba': 'انناس مربہ',
  'Petha Murabba': 'پیتھا مربہ',
  'Mixed Fruit Murabba': 'مکسڈ فروٹ مربہ',
  'Peach Murabba': 'آڑو مربہ',
  'Quince Murabba (Safarjal)': 'سفرجل مربہ',
  'Garlic Murabba': 'لہسن مربہ',
  'Papaya Murabba': 'پپیتا مربہ',
  'Cherry Murabba': 'چیری مربہ',
  'Moringa Powder': 'مورینگا پاؤڈر',
  'Ashwagandha Powder': 'اشواگندھا پاؤڈر',
  'Turmeric Powder (Curcumin)': 'ہلدی پاؤڈر (کرکمین)',
  'Spirulina Powder': 'سپیرولینا پاؤڈر',
  'Wheatgrass Powder': 'گندم گھاس پاؤڈر',
  'Psyllium Husk (Ispaghol)': 'پسلیئم ہسک (اسپغول)',
  'Barley Grass Powder': 'جَو گھاس پاؤڈر',
  'Shatavari Powder': 'شطوری پاؤڈر',
  'Triphala Powder': 'تریفلا پاؤڈر',
  'Licorice Root Powder': 'مُلحتی جذر پاؤڈر',
  'Beetroot Powder': 'چقندر پاؤڈر',
  'Neem Leaf Powder': 'نییم پتی پاؤڈر',
  'Brahmi Powder': 'برہمی پاؤڈر',
  'Amla Powder': 'املیہ پاؤڈر',
  'Matcha Green Tea Powder': 'مچا گرین ٹی پاؤڈر',
  'Dried Lavender Buds': 'ڈرائیڈ لیوینڈر بدز',
  'Peppermint Leaves': 'پپرمِنٹ لیوز',
  'Hibiscus Petals': 'ہیبیسکس پیٹلز',
  'Ginseng Root': 'جنسنگ روٹ',
  'Ginkgo Biloba': 'گنکگو بیلوبا',
  'St. Johns Wort': 'سینٹ جانز ورٹ',
  'Valerian Root': 'ویلیرین روٹ',
  'Echinacea': 'ایچیناسیہ',
  'Milk Thistle Seeds': 'ملک تھسٹل سیڈز',
  'Dandelion Root': 'ڈینڈی لائن روٹ',
  'Nettle Leaf': 'نیٹل لیف',
  'Sage Leaves': 'سیج لیوز',
  'Holy Basil (Tulsi)': 'ہولی بیسل (تُلسی)',
  'Lemon Balm': 'لیمن بالم',
  'Rosemary Needles': 'روزمری نیڈلز',
  'Himalayan Pink Salt': 'ہمالین پنک سلٹ',
  'Black Peppercorns': 'بلیک پیپر کارنز',
  'Cinnamon Sticks': 'سنامن اسٹکس',
  'Green Tea Leaves': 'گرین ٹی لیوز',
  'Organic Jaggery': 'ارگانیک گڑ',
  'Cardamom Pods': 'کارڈامم پوڈز',
  'Cloves': 'کلوز',
  'Star Anise': 'اسٹار انائس',
  'Cumin Seeds': 'زیرہ',
  'Fennel Seeds': 'سونف',
  'Bay Leaves': 'بی لیوز',
  'Mustard Seeds': 'رائی',
  'Coconut Sugar': 'کوکنٹ شوگر',
  'Turmeric Fingers': 'ہلدی انگلیاں',
  'Fenugreek Seeds': 'میتھی دانے',
  'Organic Aloe Vera Gel': 'ارگانیک ایلوویرا جیل',
  'Multani Mitti': 'ملتانی مٹی',
  'Raw Shea Butter': 'راؤ شی بٹر',
  'Apple Cider Vinegar': 'ایپل سائڈر ونیگر',
  'Cold Pressed Neem Oil': 'کوڈ پریسڈ نییم آئل',
  'Epsom Salt': 'ایپسم سلٹ',
  'Witch Hazel Extract': 'وچ ہیزل ایکسٹریکٹ',
  'Bentonite Clay': 'بینٹونائٹ کلی',
  'Castor Oil': 'کاسٹر آئل',
  'Jojoba Oil': 'جوجوبا آئل',
  'Argan Oil': 'ارگن آئل',
  'Rosehip Oil': 'روز ہپ آئل',
  'Beeswax Pellets': 'بیز ویکس پیلیٹس',
  'Activated Charcoal': 'ایکٹیویٹڈ چارکول',
  'Tea Tree Oil': 'ٹی ٹری آئل',
  'Gold Grade Shilajit': 'گولڈ گریڈ شلجیت',
  'Kashmiri Saffron (Mogra)': 'کشمیری زعفران (موگرا)',
  'Manuka Honey MGO 500+': 'مینوکا شہد ایم جی او 500+',
  'Royal Jelly Elixir': 'رائل جیلی ایلکسر',
  'Pure Sandalwood Oil': 'پیور سندل ووڈ آئل',
  'Wild Sidr Honey (Aged)': 'وائلڈ سدر شہد (ایجڈ)',
  'Ginseng Extract 10-Year': 'جنسنگ ایکسٹریکٹ 10-ایئر',
  'Pearl Powder (Edible)': 'پرل پاؤڈر (ایڈیبل)',
  'Musk Tahara (Pure)': 'مسک طہارہ (پیور)',
  'Dragon\'s Blood Resin': 'ڈریگن بلڈ ریزن',
  'White Truffle Oil': 'وائٹ ٹرفل آئل',
  'Aged Balsamic Vinegar': 'ایجڈ بالسامک ونیگر',
  'Ceremonial Matcha (AAA)': 'سیریمونیئل مچا (AAA)',
  'Pure Amber Resin': 'پیور امبر ریزن',
  'Deer Musk Oil (Synthetic-Free)': 'ڈیئر مسک آئل (سنتھیٹک فری)'
};

lines.forEach(line => {
  const cols = line.split(',');
  if (cols.length >= 7) {
    const [id, category, product_name, description, price, stock_quantity, image_url] = cols;
    if (id && category && product_name) {
      const categoryId = categoryMap[category.trim()] || category.trim().toLowerCase().replace(/ /g, '-');
      const urduName = urduNames[product_name.trim()] || '';
      products.push({
        id: id.trim(),
        name: product_name.trim(),
        price: Math.round(parseFloat(price.trim()) * 100), // Convert to paisa and round
        image: image_url.trim() || '/images/products/placeholder.jpg',
        category: categoryId,
        description: description.trim(),
        rating: 4.5,
        reviews: Math.floor(Math.random() * 100) + 10,
        inStock: parseInt(stock_quantity.trim()) > 0,
        urduName: urduName
      });
    }
  }
});

fs.writeFileSync('parsed_products.json', JSON.stringify(products, null, 2));
console.log(`Parsed ${products.length} products`);
