-- 1. Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    urdu_name TEXT,
    description TEXT,
    price FLOAT8 NOT NULL,
    category TEXT NOT NULL,
    image TEXT,
    unit TEXT DEFAULT 'grams',
    min_quantity NUMERIC DEFAULT 1,
    in_stock BOOLEAN DEFAULT true,
    rating FLOAT8 DEFAULT 0,
    reviews INTEGER DEFAULT 0,
    variants JSONB,
    bulk_discounts JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
-- Allow anyone to read products
CREATE POLICY "Allow public read access" ON public.products
    FOR SELECT USING (true);

-- Allow authenticated users (Admin) to manage products
-- NOTE: In a real app, you'd check for an 'admin' role. 
-- For now, we allow any logged-in user to manage.
CREATE POLICY "Allow authenticated management" ON public.products
    FOR ALL USING (auth.role() = 'authenticated');

-- 4. Profiles Table (Optional but recommended)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    phone_number TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- 5. Trigger for auto-creating profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, phone_number)
    VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'phone_number');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
