import { Product } from './cart-context'
export type { Product }

export interface Category {
  id: string
  slug: string
  name: string
  description: string
  icon: string
  image: string
  productCount: number
  parentId?: string
}

export const categories: Category[] = [
  // Parent Categories
  {
    id: 'natures-cureness',
    slug: 'natures-cureness',
    name: "Nature's Cureness",
    description: 'Holistic healing from the heart of Unani & Ayurveda.',
    icon: '🌿',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800&auto=format&fit=crop',
    productCount: 50,
  },
  {
    id: 'beautification',
    slug: 'beautification',
    name: 'Beautification',
    description: 'Time-tested botanical care for natural beauty.',
    icon: '✨',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdd403348?q=80&w=800&auto=format&fit=crop',
    productCount: 40,
  },
  {
    id: 'premium-collection',
    slug: 'premium-collection',
    name: 'Premium Collection',
    description: 'Exquisite, high-value natural treasures.',
    icon: '💎',
    image: 'https://images.unsplash.com/photo-1615485925763-867862f80931?q=80&w=800&auto=format&fit=crop',
    productCount: 15,
  },

  // Subcategories for Nature's Cureness
  {
    id: 'unani-specialties',
    slug: 'unani-specialties',
    name: 'Unani Specialties',
    description: 'Classic Khamiras and Maajoons for vitality.',
    icon: '🏺',
    image: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?q=80&w=800&auto=format&fit=crop',
    productCount: 10,
    parentId: 'natures-cureness',
  },
  {
    id: 'herbal-remedies',
    slug: 'herbal-remedies',
    name: 'Herbal Remedies',
    description: 'Single herbs and roots for daily health.',
    icon: '🍃',
    image: 'https://images.unsplash.com/photo-1471943311424-646960669fba?q=80&w=800&auto=format&fit=crop',
    productCount: 15,
    parentId: 'natures-cureness',
  },
  {
    id: 'immunity-boosters',
    slug: 'immunity-boosters',
    name: 'Immunity Boosters',
    description: 'Strengthen your defenses naturally.',
    icon: '🛡️',
    image: 'https://images.unsplash.com/photo-1623910363248-be2244485089?q=80&w=800&auto=format&fit=crop',
    productCount: 10,
    parentId: 'natures-cureness',
  },
    {
    id: 'digestive-wellness',
    slug: 'digestive-wellness',
    name: 'Digestive Wellness',
    description: 'Support gut health with traditional salts and seeds.',
    icon: '🌱',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=800&auto=format&fit=crop',
    productCount: 15,
    parentId: 'natures-cureness',
  },

  // Subcategories for Beautification
  {
    id: 'hair-growth',
    slug: 'hair-growth',
    name: 'Hair Growth',
    description: 'Ancient oils and powders for lush hair.',
    icon: '💇‍♀️',
    image: 'https://images.unsplash.com/photo-1522337360705-8754d8a203e8?q=80&w=800&auto=format&fit=crop',
    productCount: 10,
    parentId: 'beautification',
  },
  {
    id: 'skincare',
    slug: 'skincare',
    name: 'Skincare',
    description: 'Ubtans and floral waters for glowing skin.',
    icon: '🧴',
    image: 'https://images.unsplash.com/photo-1556228552-523cd13b86dc?q=80&w=800&auto=format&fit=crop',
    productCount: 12,
    parentId: 'beautification',
  },
  {
    id: 'glowing-solutions',
    slug: 'glowing-solutions',
    name: 'Glowing Solutions',
    description: 'Radiance from within.',
    icon: '🌟',
    image: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?q=80&w=800&auto=format&fit=crop',
    productCount: 8,
    parentId: 'beautification',
  },
  {
    id: 'weight-loss',
    slug: 'weight-loss',
    name: 'Weight Loss Solutions',
    description: 'Natural support for healthy weight management.',
    icon: '⚖️',
    image: 'https://images.unsplash.com/photo-1511690656952-34342d5c2899?q=80&w=800&auto=format&fit=crop',
    productCount: 5,
    parentId: 'beautification',
  },
  {
    id: 'weight-gain',
    slug: 'weight-gain',
    name: 'Weight Gain Solutions',
    description: 'Healthy mass building supplements.',
    icon: '💪',
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?q=80&w=800&auto=format&fit=crop',
    productCount: 5,
    parentId: 'beautification',
  },
  // --- RESTORED ORIGINAL CATEGORIES ---
  {
    id: 'adaptogens',
    slug: 'adaptogens',
    name: 'Adaptogens & Stress Relief',
    description: 'Natural stress fighters for modern life. Ashwagandha, Rhodiola & more.',
    icon: '🌿',
    image: '/images/categories/adaptogens.jpg',
    productCount: 4,
  },
  {
    id: 'immunity',
    slug: 'immunity',
    name: 'Immunity Boosters',
    description: 'Strengthen your natural defenses with elderberry, echinacea & turmeric.',
    icon: '🛡️',
    image: '/images/categories/immunity.jpg',
    productCount: 4,
  },
  {
    id: 'digestive',
    slug: 'digestive',
    name: 'Digestive Wellness',
    description: 'Support gut health with probiotics and digestive enzymes.',
    icon: '🌱',
    image: '/images/categories/digestive.jpg',
    productCount: 4,
  },
  {
    id: 'sleep',
    slug: 'sleep',
    name: 'Sleep & Relaxation',
    description: 'Natural sleep aids including valerian, chamomile & melatonin.',
    icon: '🌙',
    image: '/images/categories/sleep.jpg',
    productCount: 4,
  },
  {
    id: 'beauty',
    slug: 'beauty',
    name: 'Beauty & Skin',
    description: 'Glow from within with collagen, biotin & herbal serums.',
    icon: '✨',
    image: '/images/categories/beauty.jpg',
    productCount: 4,
  },
  {
    id: 'energy',
    slug: 'energy',
    name: 'Energy & Vitality',
    description: 'Natural energy with ginseng, maca & green supplements.',
    icon: '⚡',
    image: '/images/categories/energy.jpg',
    productCount: 4,
  },
  {
    id: 'common-items',
    slug: 'common-items',
    name: 'Common Items',
    description: 'Everyday wellness essentials and commonly used health products.',
    icon: '🏷️',
    image: '/images/categories/common-items.jpg',
    productCount: 15,
  },
  {
    id: 'herbs',
    slug: 'herbs',
    name: 'Herbs',
    description: 'Pure medicinal herbs and traditional botanical remedies.',
    icon: '🌿',
    image: '/images/categories/herbs.jpg',
    productCount: 15,
  },
  {
    id: 'natural-items',
    slug: 'natural-items',
    name: 'Natural Items',
    description: 'Authentic natural products sourced from traditional medicine.',
    icon: '🍃',
    image: '/images/categories/natural-items.jpg',
    productCount: 15,
  },
  {
    id: 'pure-arqiyat',
    slug: 'pure-arqiyat',
    name: 'Pure Arqiyat (Distillates)',
    description: 'Traditional herbal distillates for health and wellness.',
    icon: '💧',
    image: '/images/categories/pure-arqiyat.jpg',
    productCount: 15,
  },
  {
    id: 'murabba-jat',
    slug: 'murabba-jat',
    name: 'Murabba Jat (Fruit Preserves)',
    description: 'Nutritious fruit preserves made with traditional recipes.',
    icon: '🏺',
    image: '/images/categories/murabba-jat.jpg',
    productCount: 15,
  },
  {
    id: 'honey',
    slug: 'honey',
    name: 'Honey',
    description: 'Pure, natural honey varieties with therapeutic properties.',
    icon: '🍯',
    image: '/images/categories/honey.jpg',
    productCount: 15,
  },
  {
    id: 'premium-items',
    slug: 'premium-items',
    name: 'Premium Items',
    description: 'Exclusive high-quality products for discerning customers.',
    icon: '👑',
    image: '/images/categories/premium-items.jpg',
    productCount: 15,
  },
  {
    id: 'dry-fruit',
    slug: 'dry-fruit',
    name: 'Dry Fruit',
    description: 'Premium quality dried fruits and nuts for health and nutrition.',
    icon: '🥜',
    image: '/images/categories/dry-fruit.jpg',
    productCount: 15,
  },
  {
    id: 'special-powders',
    slug: 'special-powders',
    name: 'Special Powders and Kushtajaat',
    description: 'Traditional medicinal powders and metallic preparations.',
    icon: '💊',
    image: '/images/categories/special-powders.jpg',
    productCount: 15,
  },
];

export const products: Product[] = [
  // --- NATURE'S CURENESS: UNANI SPECIALTIES ---
  {
    "id": "khamira-marwareed", 
    "name": "Khamira Marwareed", 
    "price": 3500, 
    "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop", 
    "category": "unani-specialties", 
    "description": "A traditional pearl-based tonic (Khamira) used for centuries to strengthen the heart and elevate mood. Enriched with real pearls.", 
    "rating": 5.0, 
    "reviews": 120, 
    "inStock": true, 
    "badge": "Royal Unani", 
    "urduName": "خمیرہ مروارید"
  },
  {
    "id": "majoon-falasfa", 
    "name": "Majoon-e-Falasfa", 
    "price": 1800, 
    "image": "https://images.unsplash.com/photo-1590735213920-68192a48792b?q=80&w=800&auto=format&fit=crop", 
    "category": "unani-specialties", 
    "description": "An ancient 'Philosopher's Honey' blend. Renowned for boosting brain power, kidney health, and relieving joint pain.", 
    "rating": 4.8, 
    "reviews": 85, 
    "inStock": true, 
    "urduName": "معجون فلاسفہ"
  },
  {
    "id": "shilajit-resin", 
    "name": "Himalayan Shilajit Resin", 
    "price": 4500, 
    "originalPrice": 5500,
    "image": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop", 
    "category": "unani-specialties", 
    "description": "Pure, filtered black resin from the Himalayas. Known as the 'Conqueror of Mountains' for enhancing vitality and vigor.", 
    "rating": 4.9, 
    "reviews": 210, 
    "inStock": true, 
    "badge": "Best Seller", 
    "urduName": "شلاجیت"
  },

  // --- NATURE'S CURENESS: HERBAL REMEDIES ---
  {
    "id": "black-seed-oil", 
    "name": "Premium Black Seed Oil (Kalonji)", 
    "price": 1200, 
    "image": "https://images.unsplash.com/photo-1611073807909-6447c2115168?q=80&w=800&auto=format&fit=crop", 
    "category": "herbal-remedies", 
    "description": "Cold-pressed Nigella Sativa oil. A 'cure for everything except death' as per tradition. Boosts general immunity.", 
    "rating": 4.9, 
    "reviews": 450, 
    "inStock": true, 
    "badge": "Essential", 
    "urduName": "کلونجی کا تیل"
  },
  {
    "id": "ashwagandha-gold", 
    "name": "Ashwagandha Gold Extract", 
    "price": 2499, 
    "originalPrice": 3299, 
    "image": "https://images.unsplash.com/photo-1611073807909-6447c2115168?q=80&w=800&auto=format&fit=crop", 
    "category": "herbal-remedies", 
    "description": "Premium KSM-66 extract. An ancient adaptogen used to combat stress and build strength.", 
    "rating": 4.8, 
    "reviews": 342, 
    "inStock": true, 
    "badge": "Best Seller", 
    "urduName": "اشوگندھا گولڈ"
  },

  // --- NATURE'S CURENESS: IMMUNITY ---
  {
    "id": "turmeric-golden", 
    "name": "Golden Turmeric Capsules", 
    "price": 1599, 
    "image": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop", 
    "category": "immunity-boosters", 
    "description": "Curcumin enriched with black pepper. The 'Golden Healer' of traditional medicine.", 
    "rating": 4.7, 
    "reviews": 312, 
    "inStock": true, 
    "urduName": "ہلدی کیپسول"
  },
  {
    "id": "reishi-mushroom", 
    "name": "Reishi Mushroom Tincture", 
    "price": 2999, 
    "originalPrice": 3499, 
    "image": "https://images.unsplash.com/photo-1623910363248-be2244485089?q=80&w=800&auto=format&fit=crop", 
    "category": "immunity-boosters", 
    "description": "Functional mushroom extract for longevity and spirit calming.", 
    "rating": 4.9, 
    "reviews": 278, 
    "inStock": true, 
    "badge": "Premium", 
    "urduName": "ریشی مشروم"
  },

  // --- BEAUTIFICATION: HAIR GROWTH ---
  {
    "id": "bhringraj-oil-pure", 
    "name": "Mahabhringraj Oil", 
    "price": 1499, 
    "image": "https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=800&auto=format&fit=crop", 
    "category": "hair-growth", 
    "description": "Known as 'Keshraj' or King of Hair. Traditional preparation for preventing graying and hair fall.", 
    "rating": 4.9, 
    "reviews": 230, 
    "inStock": true, 
    "badge": "Ayurvedic", 
    "urduName": "بھرنگراج تیل"
  },
  {
    "id": "egg-oil", 
    "name": "Roghan-e-Baiza-e-Murgh (Egg Oil)", 
    "price": 1899, 
    "image": "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?q=80&w=800&auto=format&fit=crop", 
    "category": "hair-growth", 
    "description": "Concentrated extract from egg yolks. A Unani secret for regrowing hair spots and strengthening follicles.", 
    "rating": 4.7, 
    "reviews": 112, 
    "inStock": true, 
    "urduName": "روغن بیضہ مرغ"
  },
  {
    "id": "sikakai-shampoo", 
    "name": "Reetha & Sikakai Cleanser", 
    "price": 899, 
    "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=800&auto=format&fit=crop", 
    "category": "hair-growth", 
    "description": "Natural soapnut and acacia blend. The traditional way to wash hair without chemicals.", 
    "rating": 4.6, 
    "reviews": 180, 
    "inStock": true, 
    "urduName": "ریٹھا اور سکاکائی"
  },

  // --- BEAUTIFICATION: SKINCARE ---
  {
    "id": "husn-e-yousuf", 
    "name": "Husn-e-Yousuf Ubtan", 
    "price": 1200, 
    "image": "https://images.unsplash.com/photo-1556228552-523cd13b86dc?q=80&w=800&auto=format&fit=crop", 
    "category": "skincare", 
    "description": "Traditional beautifying powder blend. Used by brides for a radiant, spot-free complexion.", 
    "rating": 4.9, 
    "reviews": 310, 
    "inStock": true, 
    "badge": "Bridal Choice", 
    "urduName": "حسن یوسف"
  },
  {
    "id": "kumkumadi-tailam", 
    "name": "Kumkumadi Tailam", 
    "price": 3200, 
    "originalPrice": 4000,
    "image": "https://images.unsplash.com/photo-1608248597279-f99d160bfbc8?q=80&w=800&auto=format&fit=crop", 
    "category": "skincare", 
    "description": "The 'Miraculous Saffron Oil'. A classical Ayurvedic formula for skin rejuvenation and glow.", 
    "rating": 5.0, 
    "reviews": 95, 
    "inStock": true, 
    "badge": "Luxury", 
    "urduName": "کمکمادی تیلم"
  },
  {
    "id": "rose-water-kannauj", 
    "name": "Pure Rose Water (Kannauj)", 
    "price": 899, 
    "image": "https://images.unsplash.com/photo-1556228720-1987d7d24295?q=80&w=800&auto=format&fit=crop", 
    "category": "skincare", 
    "description": "Deg-distilled rose water from the perfume capital of India. Natural skin toner.", 
    "rating": 4.8, 
    "reviews": 400, 
    "inStock": true, 
    "urduName": "عرق گلاب"
  },

  // --- BEAUTIFICATION: WEIGHT LOSS ---
  {
    "id": "triphala-powder", 
    "name": "Organic Triphala Powder", 
    "price": 999, 
    "image": "https://images.unsplash.com/photo-1616641697268-2a74c449553f?q=80&w=800&auto=format&fit=crop", 
    "category": "weight-loss", 
    "description": "Three-fruit blend (Amla, Haritaki, Bibhitaki). Gentle detoxifier that improves metabolism.", 
    "rating": 4.7, 
    "reviews": 220, 
    "inStock": true, 
    "urduName": "ترپھلا پاؤڈر"
  },
  {
    "id": "lukman-hayat-oil", 
    "name": "Lukman-e-Hayat Massage Oil", 
    "price": 1500, 
    "image": "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=800&auto=format&fit=crop", 
    "category": "weight-loss", 
    "description": "Traditional massage oil to help tone the body and burn cellulite.", 
    "rating": 4.5, 
    "reviews": 130, 
    "inStock": true, 
    "urduName": "لقمان حیات تیل"
  },

  // --- BEAUTIFICATION: WEIGHT GAIN ---
  {
    "id": "mass-gainer-herbal", 
    "name": "Herbal Mass Gainer", 
    "price": 2499, 
    "originalPrice": 2999, 
    "image": "https://images.unsplash.com/photo-1579722820308-d74e571900a9?q=80&w=800&auto=format&fit=crop", 
    "category": "weight-gain", 
    "description": "A blend of Ashwagandha, Shatavari, and White Musli to build healthy body mass.", 
    "rating": 4.6, 
    "reviews": 150, 
    "inStock": true, 
    "urduName": "ہربل ماس گینر"
  },
  {
    "id": "chyawanprash-gold", 
    "name": "Royal Chyawanprash", 
    "price": 1600, 
    "image": "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=800&auto=format&fit=crop", 
    "category": "weight-gain", 
    "description": "Traditional gooseberry jam with 40+ herbs. Builds strength, immunity, and healthy weight.", 
    "rating": 4.8, 
    "reviews": 290, 
    "inStock": true, 
    "urduName": "چونپراش"
  },

  // --- PREMIUM COLLECTION ---
  {
    "id": "manuka-honey", 
    "name": "Manuka Honey MGO 850+", 
    "price": 9500, 
    "image": "https://images.unsplash.com/photo-1587049352851-8d4e8918dcf1?q=80&w=800&auto=format&fit=crop", 
    "category": "premium-collection", 
    "description": "Ultra-premium medicinal honey from New Zealand. Potent antibacterial properties.", 
    "rating": 5.0, 
    "reviews": 45, 
    "inStock": true, 
    "badge": "Luxury", 
    "urduName": "مینوکا شہد"
  },
  {
    "id": "kashmiri-saffron", 
    "name": "Kashmiri Mogra Saffron", 
    "price": 8000, 
    "image": "https://images.unsplash.com/photo-1502330023388-f97021590ddf?q=80&w=800&auto=format&fit=crop", 
    "category": "premium-collection", 
    "description": "The world's finest saffron threads. 5g. Used for glowing skin and health.", 
    "rating": 5.0, 
    "reviews": 60, 
    "inStock": true, 
    "urduName": "کشمیری زعفران"
  },
  // --- RESTORED ORIGINAL PRODUCTS BATCH 1 ---
  {"id": "rhodiola-rosea", "name": "Rhodiola Rosea Complex", "price": 1899, "originalPrice": 2499, "image": "/images/products/rhodiola.jpg", "category": "adaptogens", "description": "Adaptogenic herb for energy and stress resistance. 90 capsules.", "rating": 4.6, "reviews": 189, "inStock": true, "urduName": "رہیوڈیولا روزیا"},
  {"id": "holy-basil", "name": "Holy Basil (Tulsi) Extract", "price": 1299, "image": "/images/products/tulsi.jpg", "category": "adaptogens", "description": "Sacred herb for stress relief and respiratory health. 60 capsules.", "rating": 4.7, "reviews": 156, "inStock": true, "urduName": "تلسی"},
  {"id": "elderberry-syrup", "name": "Elderberry Immune Syrup", "price": 1799, "image": "/images/products/elderberry.jpg", "category": "immunity", "description": "Organic elderberry syrup with honey and zinc. 200ml bottle.", "rating": 4.8, "reviews": 423, "inStock": true, "badge": "Best Seller", "urduName": "ایلڈر بیری"},
  {"id": "vitamin-c-complex", "name": "Vitamin C + Zinc Complex", "price": 999, "originalPrice": 1299, "image": "/images/products/vitamin-c.jpg", "category": "immunity", "description": "High-potency vitamin C with zinc for immune support. 120 tablets.", "rating": 4.5, "reviews": 567, "inStock": true, "urduName": "وٹامن سی"},
  {"id": "echinacea-drops", "name": "Echinacea Immune Drops", "price": 1399, "originalPrice": 1699, "image": "/images/products/echinacea.jpg", "category": "immunity", "description": "Concentrated echinacea extract for seasonal wellness. 50ml.", "rating": 4.4, "reviews": 198, "inStock": true, "urduName": "ایکی نی شیا"},
  {"id": "probiotic-50b", "name": "Probiotic 50 Billion CFU", "price": 2299, "image": "/images/products/probiotic.jpg", "category": "digestive", "description": "15 probiotic strains for complete gut health. 30 delayed-release capsules.", "rating": 4.9, "reviews": 445, "inStock": true, "badge": "Top Rated", "urduName": "پروبائیوٹک"},
  {"id": "digestive-enzymes", "name": "Complete Digestive Enzymes", "price": 1499, "image": "/images/products/enzymes.jpg", "category": "digestive", "description": "Full-spectrum enzymes for optimal digestion. 90 capsules.", "rating": 4.6, "reviews": 234, "inStock": true, "urduName": "ہاضمے کے انزائمز"},
  {"id": "triphala-powder-digestive", "name": "Organic Triphala Powder", "price": 899, "image": "/images/products/triphala.jpg", "category": "digestive", "description": "Traditional Ayurvedic blend for digestive health. 200g jar.", "rating": 4.5, "reviews": 178, "inStock": true, "urduName": "ترپھلا پاؤڈر"},
  {"id": "ginger-root", "name": "Ginger Root Extract", "price": 1199, "originalPrice": 1499, "image": "/images/products/ginger.jpg", "category": "digestive", "description": "Concentrated ginger for digestive comfort. 60 capsules.", "rating": 4.7, "reviews": 289, "inStock": true, "urduName": "ادرک کی جڑ"},
  {"id": "sleep-blend", "name": "Deep Sleep Herbal Blend", "price": 1899, "originalPrice": 2299, "image": "/images/products/sleep-blend.jpg", "category": "sleep", "description": "Valerian, chamomile & passionflower for restful sleep. 60 capsules.", "rating": 4.8, "reviews": 512, "inStock": true, "badge": "Best Seller", "urduName": "گہری نیند"},
  {"id": "melatonin-gummies", "name": "Melatonin Sleep Gummies", "price": 1299, "image": "/images/products/melatonin.jpg", "category": "sleep", "description": "Delicious berry-flavored gummies for better sleep. 60 gummies.", "rating": 4.6, "reviews": 378, "inStock": true, "urduName": "میلاٹونن"},
  {"id": "lavender-oil", "name": "Lavender Essential Oil", "price": 799, "image": "/images/products/lavender.jpg", "category": "sleep", "description": "Pure lavender oil for aromatherapy relaxation. 15ml bottle.", "rating": 4.9, "reviews": 423, "inStock": true, "urduName": "لیوینڈر آئل"},
  {"id": "magnesium-glycinate", "name": "Magnesium Glycinate", "price": 1599, "image": "/images/products/magnesium.jpg", "category": "sleep", "description": "Highly absorbable magnesium for relaxation. 120 capsules.", "rating": 4.7, "reviews": 267, "inStock": true, "urduName": "میگنیشیم"},
  {"id": "collagen-peptides", "name": "Marine Collagen Peptides", "price": 3499, "originalPrice": 4299, "image": "/images/products/collagen.jpg", "category": "beauty", "description": "Premium marine collagen for skin elasticity. 300g powder.", "rating": 4.9, "reviews": 634, "inStock": true, "badge": "Premium", "urduName": "میرین کولیجن"},
  {"id": "biotin-10000", "name": "Biotin 10,000mcg", "price": 1199, "image": "/images/products/biotin.jpg", "category": "beauty", "description": "High-potency biotin for hair, skin & nails. 90 tablets.", "rating": 4.6, "reviews": 456, "inStock": true, "urduName": "بائیوٹن"},
  {"id": "hyaluronic-acid", "name": "Hyaluronic Acid Serum", "price": 1999, "originalPrice": 2499, "image": "/images/products/hyaluronic.jpg", "category": "beauty", "description": "Intensive hydration serum for plump skin. 30ml bottle.", "rating": 4.8, "reviews": 389, "inStock": true, "urduName": "ہائلورونک ایسڈ"},
  {"id": "vitamin-e-oil", "name": "Natural Vitamin E Oil", "price": 899, "image": "/images/products/vitamin-e.jpg", "category": "beauty", "description": "Antioxidant-rich oil for skin nourishment. 50ml bottle.", "rating": 4.5, "reviews": 234, "inStock": true, "urduName": "وٹامن ای"},
  {"id": "korean-ginseng", "name": "Korean Red Ginseng", "price": 2799, "originalPrice": 3299, "image": "/images/products/ginseng.jpg", "category": "energy", "description": "6-year aged Korean red ginseng extract. 60 capsules.", "rating": 4.8, "reviews": 367, "inStock": true, "badge": "Premium", "urduName": "کورین ریڈ جِنسنگ"},
  {"id": "maca-root", "name": "Organic Maca Root", "price": 1499, "image": "/images/products/maca.jpg", "category": "energy", "description": "Peruvian maca for energy and stamina. 90 capsules.", "rating": 4.6, "reviews": 289, "inStock": true, "urduName": "ماکا جڑ"},
  {"id": "green-tea-extract", "name": "Green Tea Extract EGCG", "price": 1299, "originalPrice": 1599, "image": "/images/products/green-tea.jpg", "category": "energy", "description": "Standardized EGCG for natural energy boost. 60 capsules.", "rating": 4.5, "reviews": 198, "inStock": true, "urduName": "سبز چائے کا نچوڑ"},
  {"id": "spirulina-powder-energy", "name": "Organic Spirulina Powder", "price": 1899, "image": "/images/products/spirulina.jpg", "category": "energy", "description": "Nutrient-dense superfood for daily vitality. 250g jar.", "rating": 4.7, "reviews": 312, "inStock": true, "urduName": "اسپرولینا پاؤڈر"},
  // --- RESTORED ORIGINAL PRODUCTS BATCH 2 (IDs 1-60) ---
  {"id": "1", "name": "Sidr Honey (Premium)", "price": 4500.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Rare medicinal honey from Sidr trees.", "rating": 4.5, "reviews": 60, "inStock": true, "urduName": "سدر شہد"},
  {"id": "2", "name": "Acacia Honey", "price": 2500.0, "image": "https://images.unsplash.com/photo-1558614334-97241aa4444e", "category": "honey", "description": "Clear, mild honey that stays liquid.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "اکیشیا شہد"},
  {"id": "3", "name": "Wild Forest Honey", "price": 3000.0, "image": "https://images.unsplash.com/photo-1471943311424-646960669fba", "category": "honey", "description": "Dark, rich honey from organic forest nectar.", "rating": 4.5, "reviews": 85, "inStock": true, "urduName": "جنگلی شہد"},
  {"id": "4", "name": "Clover Honey", "price": 1500.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Classic sweet floral honey for daily use.", "rating": 4.5, "reviews": 210, "inStock": true, "urduName": "کلور شہد"},
  {"id": "5", "name": "Manuka Style Honey", "price": 6000.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "High-activity honey for immune support.", "rating": 4.5, "reviews": 40, "inStock": true, "urduName": "مانوکا سٹائل شہد"},
  {"id": "6", "name": "Eucalyptus Honey", "price": 2200.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Herbal notes, great for respiratory health.", "rating": 4.5, "reviews": 90, "inStock": true, "urduName": "یوکلپٹس شہد"},
  {"id": "7", "name": "Orange Blossom Honey", "price": 1800.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Light citrus aroma, perfect for tea.", "rating": 4.5, "reviews": 100, "inStock": true, "urduName": "اورنج بلوسم شہد"},
  {"id": "8", "name": "Buckwheat Honey", "price": 2800.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Strong, malty flavor rich in iron.", "rating": 4.5, "reviews": 50, "inStock": true, "urduName": "بک وہیٹ شہد"},
  {"id": "9", "name": "Neem Honey", "price": 3500.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Bitter-sweet honey with anti-inflammatory properties.", "rating": 4.5, "reviews": 55, "inStock": true, "urduName": "نیم شہد"},
  {"id": "10", "name": "Sunflower Honey", "price": 1200.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Bright yellow honey, high in glucose.", "rating": 4.5, "reviews": 130, "inStock": true, "urduName": "سن فلاور شہد"},
  {"id": "11", "name": "Lavender Honey", "price": 3200.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Premium honey infused with lavender nectar.", "rating": 4.5, "reviews": 65, "inStock": true, "urduName": "لیوینڈر شہد"},
  {"id": "12", "name": "Thyme Honey", "price": 3800.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Intense herbal flavor from the Mediterranean.", "rating": 4.5, "reviews": 35, "inStock": true, "urduName": "تھائیم شہد"},
  {"id": "13", "name": "Black Seed Honey", "price": 4000.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Honey blended with Kalonji extracts.", "rating": 4.5, "reviews": 70, "inStock": true, "urduName": "کلونجی شہد"},
  {"id": "14", "name": "Comb Honey", "price": 3400.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Pure honey served inside the natural wax comb.", "rating": 4.5, "reviews": 30, "inStock": true, "urduName": "کومب شہد"},
  {"id": "15", "name": "Ginger Infused Honey", "price": 2000.0, "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38", "category": "honey", "description": "Zesty honey for digestion and sore throats.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "ادرک والا شہد"},
  {"id": "16", "name": "Mamra Almonds", "price": 5500.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "High-oil content almonds for brain health.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "ممرا بادام"},
  {"id": "17", "name": "Walnut Kernels", "price": 4000.0, "image": "https://images.unsplash.com/photo-1585002181205-09f196924d67", "category": "dry-fruit", "description": "Premium light-colored halves.", "rating": 4.5, "reviews": 90, "inStock": true, "urduName": "اخروٹ"},
  {"id": "18", "name": "Roasted Cashews", "price": 3000.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Salted and roasted for a perfect snack.", "rating": 4.5, "reviews": 160, "inStock": true, "urduName": "بھنے ہوئے کاجو"},
  {"id": "19", "name": "Pistachios (Roasted)", "price": 4500.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Shell-on premium Iranian pistachios.", "rating": 4.5, "reviews": 100, "inStock": true, "urduName": "پستے"},
  {"id": "20", "name": "Pine Nuts (Chilgoza)", "price": 8500.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Wild-harvested, buttery texture.", "rating": 4.5, "reviews": 50, "inStock": true, "urduName": "چلغوزہ"},
  {"id": "21", "name": "Dried Figs (Anjeer)", "price": 2500.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Soft, fiber-rich premium figs.", "rating": 4.5, "reviews": 120, "inStock": true, "urduName": "انجیر"},
  {"id": "22", "name": "Green Raisins", "price": 1200.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Sweet, sun-dried seedless raisins.", "rating": 4.5, "reviews": 210, "inStock": true, "urduName": "کشمش"},
  {"id": "23", "name": "Black Raisins", "price": 1500.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Seedless, high in antioxidants.", "rating": 4.5, "reviews": 190, "inStock": true, "urduName": "کشمش"},
  {"id": "24", "name": "Apricots (Dried)", "price": 2000.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Sweet and tangy organic apricots.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "خوبانی"},
  {"id": "25", "name": "Dates (Ajwa)", "price": 5000.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "The holy dates of Medina, rich in nutrients.", "rating": 4.5, "reviews": 70, "inStock": true, "urduName": "عجوہ"},
  {"id": "26", "name": "Dates (Medjool)", "price": 3500.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Large, caramel-like luxury dates.", "rating": 4.5, "reviews": 80, "inStock": true, "urduName": "مدجول"},
  {"id": "27", "name": "Hazelnuts", "price": 3800.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Raw, skinless premium hazelnuts.", "rating": 4.5, "reviews": 60, "inStock": true, "urduName": "ہیزل نٹس"},
  {"id": "28", "name": "Macadamia Nuts", "price": 7000.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "The king of nuts, buttery and rich.", "rating": 4.5, "reviews": 40, "inStock": true, "urduName": "ماکا ڈیمیا نٹس"},
  {"id": "29", "name": "Pecans", "price": 4200.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "Sweet, earthy nut halves.", "rating": 4.5, "reviews": 55, "inStock": true, "urduName": "پیکانز"},
  {"id": "30", "name": "Brazil Nuts", "price": 4800.0, "image": "https://images.unsplash.com/photo-1508817628294-40076cf6b1b5", "category": "dry-fruit", "description": "High in Selenium, raw and crunchy.", "rating": 4.5, "reviews": 50, "inStock": true, "urduName": "برازیل نٹس"},
  {"id": "31", "name": "Arq-e-Gulab", "price": 800.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Pure steam-distilled Rose water.", "rating": 4.5, "reviews": 310, "inStock": true, "urduName": "عرق گلاب"},
  {"id": "32", "name": "Arq-e-Kasni", "price": 1000.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Distilled Chicory for liver health.", "rating": 4.5, "reviews": 160, "inStock": true, "urduName": "عرق کاسنی"},
  {"id": "33", "name": "Arq-e-Mako", "price": 1000.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Distilled Nightshade for inflammation.", "rating": 4.5, "reviews": 160, "inStock": true, "urduName": "عرق مکو"},
  {"id": "34", "name": "Arq-e-Badiyan", "price": 900.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Fennel distillate for digestion.", "rating": 4.5, "reviews": 210, "inStock": true, "urduName": "عرق بادیان"},
  {"id": "35", "name": "Arq-e-Nana", "price": 700.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Mint distillate for cooling effects.", "rating": 4.5, "reviews": 260, "inStock": true, "urduName": "عرق پودینہ"},
  {"id": "36", "name": "Arq-e-Ajwain", "price": 900.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Carom seed distillate for gastric relief.", "rating": 4.5, "reviews": 190, "inStock": true, "urduName": "عجوہ"},
  {"id": "37", "name": "Arq-e-Chaharmaza", "price": 1200.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "A blend of four seeds for vitality.", "rating": 4.5, "reviews": 130, "inStock": true, "urduName": "عرق چہار مغز"},
  {"id": "38", "name": "Arq-e-Mundiyan", "price": 1100.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Sphaeranthus distillate for blood purification.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "عرق منڈی"},
  {"id": "39", "name": "Arq-e-Afsanteen", "price": 1300.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Wormwood distillate for stomach health.", "rating": 4.5, "reviews": 90, "inStock": true, "urduName": "عرق افسنتین"},
  {"id": "40", "name": "Arq-e-Ushba", "price": 1500.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Sarsaparilla distillate for skin health.", "rating": 4.5, "reviews": 80, "inStock": true, "urduName": "عرق عشبہ"},
  {"id": "41", "name": "Arq-e-Nilofar", "price": 1400.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108", "category": "pure-arqiyat", "description": "Lotus distillate for heart cooling.", "rating": 4.5, "reviews": 100, "inStock": true, "urduName": "عرق نیلوفر"},
  {"id": "42", "name": "Arq-e-Gaozaban", "price": 1200.0, "image": "https://example.com/arq12.jpg", "category": "pure-arqiyat", "description": "Borage distillate for mental clarity.", "rating": 4.5, "reviews": 120, "inStock": true, "urduName": "عرق گاؤزباں"},
  {"id": "43", "name": "Arq-e-Shahtara", "price": 1000.0, "image": "https://example.com/arq13.jpg", "category": "pure-arqiyat", "description": "Fumitory distillate for detoxification.", "rating": 4.5, "reviews": 140, "inStock": true, "urduName": "عرق شاہترہ"},
  {"id": "44", "name": "Arq-e-Bahar-e-Naranj", "price": 1600.0, "image": "https://example.com/arq14.jpg", "category": "pure-arqiyat", "description": "Orange blossom water for nerves.", "rating": 4.5, "reviews": 70, "inStock": true, "urduName": "عرق بہار نارنج"},
  {"id": "45", "name": "Arq-e-Murakkab", "price": 1800.0, "image": "https://example.com/arq15.jpg", "category": "pure-arqiyat", "description": "Compound distillate for overall wellness.", "rating": 4.5, "reviews": 60, "inStock": true, "urduName": "عرق مرکب"},
  {"id": "46", "name": "Amla Murabba", "price": 1200.0, "image": "https://example.com/murabba1.jpg", "category": "murabba-jat", "description": "Indian Gooseberry preserve, high Vit C.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "آملہ مربہ"},
  {"id": "47", "name": "Apple Murabba", "price": 1500.0, "image": "https://example.com/murabba2.jpg", "category": "murabba-jat", "description": "Delicious apple preserve for heart health.", "rating": 4.5, "reviews": 90, "inStock": true, "urduName": "سیب کا مربہ"},
  {"id": "48", "name": "Carrot Murabba", "price": 1000.0, "image": "https://example.com/murabba3.jpg", "category": "murabba-jat", "description": "Gajjar preserve for eyesight.", "rating": 4.5, "reviews": 130, "inStock": true, "urduName": "گاجر کا مربہ"},
  {"id": "49", "name": "Harar Murabba", "price": 1400.0, "image": "https://example.com/murabba4.jpg", "category": "murabba-jat", "description": "Black Myrobalan preserve for stomach.", "rating": 4.5, "reviews": 100, "inStock": true, "urduName": "ہڑہڑ کا مربہ"},
  {"id": "50", "name": "Ginger Murabba", "price": 1600.0, "image": "https://example.com/murabba5.jpg", "category": "murabba-jat", "description": "Spicy ginger preserve for digestion.", "rating": 4.5, "reviews": 80, "inStock": true, "urduName": "ادرک کا مربہ"},
  {"id": "51", "name": "Bael Murabba", "price": 1800.0, "image": "https://example.com/murabba6.jpg", "category": "murabba-jat", "description": "Stone apple preserve for gut health.", "rating": 4.5, "reviews": 70, "inStock": true, "urduName": "بیل کا مربہ"},
  {"id": "52", "name": "Mango Murabba", "price": 1300.0, "image": "https://example.com/murabba7.jpg", "category": "murabba-jat", "description": "Sweet raw mango preserve.", "rating": 4.5, "reviews": 160, "inStock": true, "urduName": "آم کا مربہ"},
  {"id": "53", "name": "Pineapple Murabba", "price": 2000.0, "image": "https://example.com/murabba8.jpg", "category": "murabba-jat", "description": "Exotic fruit preserve with enzymes.", "rating": 4.5, "reviews": 60, "inStock": true, "urduName": "سیب کا مربہ"},
  {"id": "54", "name": "Petha Murabba", "price": 900.0, "image": "https://example.com/murabba9.jpg", "category": "murabba-jat", "description": "Ash gourd sweet preserve.", "rating": 4.5, "reviews": 210, "inStock": true, "urduName": "پیٹھا مربہ"},
  {"id": "55", "name": "Mixed Fruit Murabba", "price": 2200.0, "image": "https://example.com/murabba10.jpg", "category": "murabba-jat", "description": "Assorted fruits in honey syrup.", "rating": 4.5, "reviews": 50, "inStock": true, "urduName": "مکس فروٹ مربہ"},
  {"id": "56", "name": "Peach Murabba", "price": 1700.0, "image": "https://example.com/murabba11.jpg", "category": "murabba-jat", "description": "Soft peach halves in syrup.", "rating": 4.5, "reviews": 65, "inStock": true, "urduName": "آڑو کا مربہ"},
  {"id": "57", "name": "Quince Murabba (Safarjal)", "price": 2500.0, "image": "https://example.com/murabba12.jpg", "category": "murabba-jat", "description": "Traditional remedy for heart and lung.", "rating": 4.5, "reviews": 40, "inStock": true, "urduName": "سفرجل کا مربہ"},
  {"id": "58", "name": "Garlic Murabba", "price": 1900.0, "image": "https://example.com/murabba13.jpg", "category": "murabba-jat", "description": "Pickled sweet garlic for blood pressure.", "rating": 4.5, "reviews": 55, "inStock": true, "urduName": "لہسن کا مربہ"},
  {"id": "59", "name": "Papaya Murabba", "price": 1400.0, "image": "https://example.com/murabba14.jpg", "category": "murabba-jat", "description": "Digestive aid papaya preserve.", "rating": 4.5, "reviews": 85, "inStock": true, "urduName": "پپیتا مربہ"},
  {"id": "60", "name": "Cherry Murabba", "price": 2400.0, "image": "https://example.com/murabba15.jpg", "category": "murabba-jat", "description": "Sweetened whole cherries.", "rating": 4.5, "reviews": 45, "inStock": true, "urduName": "چیری مربہ"},
  // --- RESTORED ORIGINAL PRODUCTS BATCH 3 (IDs 61-120) ---
  {"id": "61", "name": "Moringa Powder", "price": 1500.0, "image": "https://images.unsplash.com/photo-1515696955266-4f67e13219e8", "category": "special-powders", "description": "Superfood green leaf powder.", "rating": 4.5, "reviews": 210, "inStock": true, "urduName": "سوہانجنا پاؤڈر"},
  {"id": "62", "name": "Ashwagandha Powder", "price": 1800.0, "image": "https://example.com/powder2.jpg", "category": "special-powders", "description": "Adaptogen for stress relief.", "rating": 4.5, "reviews": 160, "inStock": true, "urduName": "اشوگندھا پاؤڈر"},
  {"id": "63", "name": "Turmeric Powder (Curcumin)", "price": 1000.0, "image": "https://example.com/powder3.jpg", "category": "special-powders", "description": "High-potency organic turmeric.", "rating": 4.5, "reviews": 310, "inStock": true, "urduName": "ہلدی پاؤڈر"},
  {"id": "64", "name": "Spirulina Powder", "price": 2500.0, "image": "https://example.com/powder4.jpg", "category": "special-powders", "description": "Blue-green algae superfood.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "اسپرولینا پاؤڈر"},
  {"id": "65", "name": "Wheatgrass Powder", "price": 2000.0, "image": "https://example.com/powder5.jpg", "category": "special-powders", "description": "Detoxifying chlorophyll boost.", "rating": 4.5, "reviews": 130, "inStock": true, "urduName": "گندم کی گھاس کا پاؤڈر"},
  {"id": "66", "name": "Psyllium Husk (Ispaghol)", "price": 1200.0, "image": "https://example.com/powder6.jpg", "category": "special-powders", "description": "Pure dietary fiber for digestion.", "rating": 4.5, "reviews": 410, "inStock": true, "urduName": "اسپغول کی بھوسی"},
  {"id": "67", "name": "Barley Grass Powder", "price": 1900.0, "image": "https://example.com/powder7.jpg", "category": "special-powders", "description": "Mineral-rich alkaline powder.", "rating": 4.5, "reviews": 120, "inStock": true, "urduName": "جو کی گھاس کا پاؤڈر"},
  {"id": "68", "name": "Shatavari Powder", "price": 2200.0, "image": "https://example.com/powder8.jpg", "category": "special-powders", "description": "Hormonal balance for women.", "rating": 4.5, "reviews": 90, "inStock": true, "urduName": "ستاوری پاؤڈر"},
  {"id": "69", "name": "Triphala Powder", "price": 1400.0, "image": "https://example.com/powder9.jpg", "category": "special-powders", "description": "Ayurvedic blend for gut cleanse.", "rating": 4.5, "reviews": 170, "inStock": true, "urduName": "ترپھلا پاؤڈر"},
  {"id": "70", "name": "Licorice Root Powder", "price": 1300.0, "image": "https://example.com/powder10.jpg", "category": "special-powders", "description": "Soothes throat and stomach.", "rating": 4.5, "reviews": 150, "inStock": true, "urduName": "ملٹھی پاؤڈر"},
  {"id": "71", "name": "Beetroot Powder", "price": 1700.0, "image": "https://example.com/powder11.jpg", "category": "special-powders", "description": "Natural energy and BP support.", "rating": 4.5, "reviews": 140, "inStock": true, "urduName": "چقندر پاؤڈر"},
  {"id": "72", "name": "Neem Leaf Powder", "price": 1100.0, "image": "https://example.com/powder12.jpg", "category": "special-powders", "description": "Blood purifier and skin support.", "rating": 4.5, "reviews": 190, "inStock": true, "urduName": "نیم کے پتوں کا پاؤڈر"},
  {"id": "73", "name": "Brahmi Powder", "price": 2400.0, "image": "https://example.com/powder13.jpg", "category": "special-powders", "description": "Memory and focus enhancer.", "rating": 4.5, "reviews": 80, "inStock": true, "urduName": "براہمی پاؤڈر"},
  {"id": "74", "name": "Amla Powder", "price": 1200.0, "image": "https://example.com/powder14.jpg", "category": "special-powders", "description": "Dried gooseberry for hair and skin.", "rating": 4.5, "reviews": 260, "inStock": true, "urduName": "آملہ پاؤڈر"},
  {"id": "75", "name": "Matcha Green Tea Powder", "price": 3500.0, "image": "https://example.com/powder15.jpg", "category": "special-powders", "description": "High-antioxidant ceremonial grade.", "rating": 4.5, "reviews": 70, "inStock": true, "urduName": "ماچا گرین ٹی پاؤڈر"},
  {"id": "76", "name": "Dried Lavender Buds", "price": 1200.0, "image": "https://images.unsplash.com/photo-1597481499750-3e6b22637e12", "category": "herbs", "description": "Fragrant culinary-grade lavender for tea and aromatics.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "لیوینڈر کے پھول"},
  {"id": "77", "name": "Peppermint Leaves", "price": 900.0, "image": "https://example.com/herbs2.jpg", "category": "herbs", "description": "Dried organic peppermint for refreshing herbal infusions.", "rating": 4.5, "reviews": 160, "inStock": true, "urduName": "پودینہ کے پتے"},
  {"id": "78", "name": "Hibiscus Petals", "price": 1100.0, "image": "https://example.com/herbs3.jpg", "category": "herbs", "description": "Tart and vitamin-rich dried hibiscus flowers.", "rating": 4.5, "reviews": 130, "inStock": true, "urduName": "گڑھل کی پتیاں"},
  {"id": "79", "name": "Ginseng Root", "price": 4500.0, "image": "https://example.com/herbs4.jpg", "category": "herbs", "description": "Whole dried Panax ginseng root for energy and vitality.", "rating": 4.5, "reviews": 50, "inStock": true, "urduName": "جنسنگ کی جڑ"},
  {"id": "80", "name": "Ginkgo Biloba", "price": 1400.0, "image": "https://example.com/herbs5.jpg", "category": "herbs", "description": "Dried leaves known for supporting cognitive function.", "rating": 4.5, "reviews": 90, "inStock": true, "urduName": "گنکو بلوبا"},
  {"id": "81", "name": "St. Johns Wort", "price": 1300.0, "image": "https://example.com/herbs6.jpg", "category": "herbs", "description": "Traditional herb used for emotional wellness.", "rating": 4.5, "reviews": 70, "inStock": true, "urduName": "سینٹ جانز ورٹ"},
  {"id": "82", "name": "Valerian Root", "price": 1600.0, "image": "https://example.com/herbs7.jpg", "category": "herbs", "description": "Potent herb used naturally to support sleep.", "rating": 4.5, "reviews": 60, "inStock": true, "urduName": "ولیرین جڑ"},
  {"id": "83", "name": "Echinacea", "price": 1500.0, "image": "https://example.com/herbs8.jpg", "category": "herbs", "description": "Dried purple coneflower for immune system support.", "rating": 4.5, "reviews": 100, "inStock": true, "urduName": "ایکی نی شیا"},
  {"id": "84", "name": "Milk Thistle Seeds", "price": 1200.0, "image": "https://example.com/herbs9.jpg", "category": "herbs", "description": "Whole seeds used to support liver detoxification.", "rating": 4.5, "reviews": 120, "inStock": true, "urduName": "ملک تھسل کے بیج"},
  {"id": "85", "name": "Dandelion Root", "price": 1000.0, "image": "https://example.com/herbs10.jpg", "category": "herbs", "description": "Roasted root used as a natural coffee substitute.", "rating": 4.5, "reviews": 140, "inStock": true, "urduName": "کاسنی کی جڑ"},
  {"id": "86", "name": "Nettle Leaf", "price": 800.0, "image": "https://example.com/herbs11.jpg", "category": "herbs", "description": "Nutrient-dense wild-harvested stinging nettle.", "rating": 4.5, "reviews": 210, "inStock": true, "urduName": "بچھو بوٹی کے پتے"},
  {"id": "87", "name": "Sage Leaves", "price": 700.0, "image": "https://example.com/herbs12.jpg", "category": "herbs", "description": "Earthy and aromatic leaves for culinary and ritual use.", "rating": 4.5, "reviews": 190, "inStock": true, "urduName": "سیج کے پتے"},
  {"id": "88", "name": "Holy Basil (Tulsi)", "price": 1100.0, "image": "https://example.com/herbs13.jpg", "category": "herbs", "description": "The \"Queen of Herbs\" for stress and immunity.", "rating": 4.5, "reviews": 150, "inStock": true, "urduName": "تلسی"},
  {"id": "89", "name": "Lemon Balm", "price": 900.0, "image": "https://example.com/herbs14.jpg", "category": "herbs", "description": "Citrus-scented herb for relaxation and focus.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "لیمن بام"},
  {"id": "90", "name": "Rosemary Needles", "price": 600.0, "image": "https://example.com/herbs15.jpg", "category": "herbs", "description": "Dried organic rosemary for memory and cooking.", "rating": 4.5, "reviews": 260, "inStock": true, "urduName": "روزمیری"},
  {"id": "91", "name": "Himalayan Pink Salt", "price": 500.0, "image": "https://images.unsplash.com/photo-1615485500704-8e990f9900f7", "category": "common-items", "description": "Coarse mineral salt from ancient sea deposits.", "rating": 4.5, "reviews": 510, "inStock": true, "urduName": "گلابی نمک"},
  {"id": "92", "name": "Black Peppercorns", "price": 800.0, "image": "https://example.com/common2.jpg", "category": "common-items", "description": "Tellicherry whole black pepper for fresh grinding.", "rating": 4.5, "reviews": 310, "inStock": true, "urduName": "کالی مرچ"},
  {"id": "93", "name": "Cinnamon Sticks", "price": 1200.0, "image": "https://example.com/common3.jpg", "category": "common-items", "description": "Pure Ceylon cinnamon barks for flavoring.", "rating": 4.5, "reviews": 160, "inStock": true, "urduName": "دار چینی"},
  {"id": "94", "name": "Green Tea Leaves", "price": 1000.0, "image": "https://example.com/common4.jpg", "category": "common-items", "description": "Whole leaf gunpowder green tea.", "rating": 4.5, "reviews": 210, "inStock": true, "urduName": "سبز چائے کے پتے"},
  {"id": "95", "name": "Organic Jaggery", "price": 600.0, "image": "https://example.com/common5.jpg", "category": "common-items", "description": "Unrefined cane sugar with natural molasses.", "rating": 4.5, "reviews": 410, "inStock": true, "urduName": "نامیاتی گڑ"},
  {"id": "96", "name": "Cardamom Pods", "price": 2000.0, "image": "https://example.com/common6.jpg", "category": "common-items", "description": "Whole green cardamom for aromatic dishes.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "الائچی"},
  {"id": "97", "name": "Cloves", "price": 1500.0, "image": "https://example.com/common7.jpg", "category": "common-items", "description": "Strong and pungent whole dried flower buds.", "rating": 4.5, "reviews": 130, "inStock": true, "urduName": "لونگ"},
  {"id": "98", "name": "Star Anise", "price": 1400.0, "image": "https://example.com/common8.jpg", "category": "common-items", "description": "Beautiful star-shaped spice for teas and stews.", "rating": 4.5, "reviews": 90, "inStock": true, "urduName": "بادیان کا پھول"},
  {"id": "99", "name": "Cumin Seeds", "price": 700.0, "image": "https://example.com/common9.jpg", "category": "common-items", "description": "Earthy and warm aromatic spice.", "rating": 4.5, "reviews": 360, "inStock": true, "urduName": "سفید زیرہ"},
  {"id": "100", "name": "Fennel Seeds", "price": 500.0, "image": "https://example.com/common10.jpg", "category": "common-items", "description": "Sweet seeds used as a post-meal digestive.", "rating": 4.5, "reviews": 410, "inStock": true, "urduName": "سونف"},
  {"id": "101", "name": "Bay Leaves", "price": 400.0, "image": "https://example.com/common11.jpg", "category": "common-items", "description": "Whole dried laurel leaves for soups.", "rating": 4.5, "reviews": 510, "inStock": true, "urduName": "تیز پات"},
  {"id": "102", "name": "Mustard Seeds", "price": 300.0, "image": "https://example.com/common12.jpg", "category": "common-items", "description": "Small pungent seeds for pickling and tempering.", "rating": 4.5, "reviews": 610, "inStock": true, "urduName": "سرسوں کے بیج"},
  {"id": "103", "name": "Coconut Sugar", "price": 900.0, "image": "https://example.com/common13.jpg", "category": "common-items", "description": "Low-glycemic natural sweetener.", "rating": 4.5, "reviews": 260, "inStock": true, "urduName": "ناریل کی چینی"},
  {"id": "104", "name": "Turmeric Fingers", "price": 800.0, "image": "https://example.com/common14.jpg", "category": "common-items", "description": "Whole dried turmeric roots.", "rating": 4.5, "reviews": 310, "inStock": true, "urduName": "ہلدی کی گانٹھ"},
  {"id": "105", "name": "Fenugreek Seeds", "price": 600.0, "image": "https://example.com/common15.jpg", "category": "common-items", "description": "Nutty seeds used in traditional wellness.", "rating": 4.5, "reviews": 410, "inStock": true, "urduName": "میتھی دانہ"},
  {"id": "106", "name": "Organic Aloe Vera Gel", "price": 1500.0, "image": "https://example.com/natural1.jpg", "category": "natural-items", "description": "99% pure cold-pressed aloe for skin and hair.", "rating": 4.5, "reviews": 210, "inStock": true, "urduName": "ایلوویرا جیل"},
  {"id": "107", "name": "Multani Mitti", "price": 700.0, "image": "https://example.com/natural2.jpg", "category": "natural-items", "description": "Fuller's Earth clay for deep pore cleansing.", "rating": 4.5, "reviews": 310, "inStock": true, "urduName": "ملتانی مٹی"},
  {"id": "108", "name": "Raw Shea Butter", "price": 1800.0, "image": "https://example.com/natural3.jpg", "category": "natural-items", "description": "Unrefined African shea butter for intense moisture.", "rating": 4.5, "reviews": 160, "inStock": true, "urduName": "شیا بٹر"},
  {"id": "109", "name": "Apple Cider Vinegar", "price": 1200.0, "image": "https://example.com/natural4.jpg", "category": "natural-items", "description": "Organic vinegar with \"the mother\" for detox.", "rating": 4.5, "reviews": 260, "inStock": true, "urduName": "سیب کا سرکہ"},
  {"id": "110", "name": "Cold Pressed Neem Oil", "price": 1400.0, "image": "https://example.com/natural5.jpg", "category": "natural-items", "description": "Natural antiseptic oil for skin and plants.", "rating": 4.5, "reviews": 190, "inStock": true, "urduName": "نیم کا تیل"},
  {"id": "111", "name": "Epsom Salt", "price": 1000.0, "image": "https://example.com/natural6.jpg", "category": "natural-items", "description": "Pure magnesium sulfate for relaxing baths.", "rating": 4.5, "reviews": 410, "inStock": true, "urduName": "ایپسم سالٹ"},
  {"id": "112", "name": "Witch Hazel Extract", "price": 1100.0, "image": "https://example.com/natural7.jpg", "category": "natural-items", "description": "Natural alcohol-free toner for skin.", "rating": 4.5, "reviews": 230, "inStock": true, "urduName": "وچ ہی زیل"},
  {"id": "113", "name": "Bentonite Clay", "price": 1300.0, "image": "https://example.com/natural8.jpg", "category": "natural-items", "description": "Healing clay for detoxifying masks.", "rating": 4.5, "reviews": 200, "inStock": true, "urduName": "بینٹونائٹ کلے"},
  {"id": "114", "name": "Castor Oil", "price": 1600.0, "image": "https://example.com/natural9.jpg", "category": "natural-items", "description": "Thick, nutrient-rich oil for hair growth.", "rating": 4.5, "reviews": 170, "inStock": true, "urduName": "ارنڈی کا تیل"},
  {"id": "115", "name": "Jojoba Oil", "price": 2200.0, "image": "https://example.com/natural10.jpg", "category": "natural-items", "description": "Golden oil that mimics natural skin sebum.", "rating": 4.5, "reviews": 120, "inStock": true, "urduName": "جوجوبا آئل"},
  {"id": "116", "name": "Argan Oil", "price": 3000.0, "image": "https://example.com/natural11.jpg", "category": "natural-items", "description": "Liquid gold from Morocco for hair shine.", "rating": 4.5, "reviews": 100, "inStock": true, "urduName": "آرگن آئل"},
  {"id": "117", "name": "Rosehip Oil", "price": 2500.0, "image": "https://example.com/natural12.jpg", "category": "natural-items", "description": "Pure seed oil for skin rejuvenation.", "rating": 4.5, "reviews": 90, "inStock": true, "urduName": "روز ہپ آئل"},
  {"id": "118", "name": "Beeswax Pellets", "price": 1400.0, "image": "https://example.com/natural13.jpg", "category": "natural-items", "description": "Natural yellow beeswax for DIY balms.", "rating": 4.5, "reviews": 160, "inStock": true, "urduName": "شہد کی مکھی کا موم"},
  {"id": "119", "name": "Activated Charcoal", "price": 1700.0, "image": "https://example.com/natural14.jpg", "category": "natural-items", "description": "Fine powder for whitening and detox.", "rating": 4.5, "reviews": 140, "inStock": true, "urduName": "ایکٹیویٹڈ چارکول"},
  {"id": "120", "name": "Tea Tree Oil", "price": 1900.0, "image": "https://example.com/natural15.jpg", "category": "natural-items", "description": "Essential oil with powerful purifying properties.", "rating": 4.5, "reviews": 150, "inStock": true, "urduName": "ٹرفل ٹی آئل"},
  // --- RESTORED ORIGINAL PRODUCTS BATCH 4 (IDs 124-135) ---
  {"id": "124", "name": "Royal Jelly Extract", "price": 5500.0, "image": "https://example.com/premium4.jpg", "category": "premium-items", "description": "High-potency royal jelly for vitality.", "rating": 4.5, "reviews": 35, "inStock": true, "urduName": "رائل جیلی نچوڑ"},
  {"id": "125", "name": "Maca Gold Extract", "price": 2800.0, "image": "https://example.com/premium5.jpg", "category": "premium-items", "description": "Premium Peruvian Maca for energy.", "rating": 4.5, "reviews": 90, "inStock": true, "urduName": "ماکا گولڈ"},
  {"id": "126", "name": "CoQ10 Ubiquinol", "price": 4200.0, "image": "https://example.com/premium6.jpg", "category": "premium-items", "description": "Highly absorbable heart health support.", "rating": 4.5, "reviews": 60, "inStock": true, "urduName": "یو بی کوینول"},
  {"id": "127", "name": "Resveratrol Complex", "price": 3800.0, "image": "https://example.com/premium7.jpg", "category": "premium-items", "description": "Longevity and antioxidant support.", "rating": 4.5, "reviews": 45, "inStock": true, "urduName": "ریسویراٹرول"},
  {"id": "128", "name": "Astaxanthin 12mg", "price": 2500.0, "image": "https://example.com/premium8.jpg", "category": "premium-items", "description": "The world's most powerful antioxidant.", "rating": 4.5, "reviews": 110, "inStock": true, "urduName": "ایسٹازینتھین"},
  {"id": "129", "name": "Krill Oil Premium", "price": 3600.0, "image": "https://example.com/premium9.jpg", "category": "premium-items", "description": "Pure Antarctic krill for heart and brain.", "rating": 4.5, "reviews": 75, "inStock": true, "urduName": "کرل آئل"},
  {"id": "130", "name": "Glutathione Complex", "price": 4800.0, "image": "https://example.com/premium10.jpg", "category": "premium-items", "description": "Master antioxidant for skin and detox.", "rating": 4.5, "reviews": 55, "inStock": true, "urduName": "گلوٹاتھیون"},
  {"id": "131", "name": "Propolis Tincture", "price": 2200.0, "image": "https://example.com/premium11.jpg", "category": "premium-items", "description": "Natural beehive protective extract.", "rating": 4.5, "reviews": 130, "inStock": true, "urduName": "پروپولیس ٹنکچر"},
  {"id": "132", "name": "Colostrum Powder", "price": 3200.0, "image": "https://example.com/premium12.jpg", "category": "premium-items", "description": "Immune support and gut healing.", "rating": 4.5, "reviews": 85, "inStock": true, "urduName": "کولوسٹرم پاؤڈر"},
  {"id": "133", "name": "Fulvic Acid Minerals", "price": 2900.0, "image": "https://example.com/premium13.jpg", "category": "premium-items", "description": "Trace minerals for optimal absorption.", "rating": 4.5, "reviews": 65, "inStock": true, "urduName": "فلویوک ایسڈ"},
  {"id": "134", "name": "Marine Phytoplankton", "price": 4500.0, "image": "https://example.com/premium14.jpg", "category": "premium-items", "description": "Ultimate micro-algae nutrition.", "rating": 4.5, "reviews": 40, "inStock": true, "urduName": "سمندری فائیٹو پلانکٹن"},
  {"id": "135", "name": "Cordyceps Extract", "price": 3400.0, "image": "https://example.com/premium15.jpg", "category": "premium-items", "description": "Energy and stamina functional mushroom.", "rating": 4.5, "reviews": 95, "inStock": true, "urduName": "کورڈیسیپس نچوڑ"},
];

export function getProductsByCategory(categoryId: string): Product[] {
  // If accessing a main category, return all products from its subcategories too
  const category = categories.find(c => c.id === categoryId)
  if (!category) return products.filter(p => p.category === categoryId)

  // Find subcategories
  const subCategories = categories.filter(c => c.parentId === category.id)
  const categoryIds = [categoryId, ...subCategories.map(c => c.id)]

  return products.filter(p => categoryIds.includes(p.category))
}

export function getProductById(productId: string): Product | undefined {
  return products.find(p => p.id === productId)
}

export function getCategoryById(categoryId: string): Category | undefined {
  return categories.find(c => c.id === categoryId)
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.badge || p.rating >= 4.8).slice(0, 8)
}

export function formatPrice(price: number): string {
  return `Rs. ${price.toLocaleString('en-IN')}`
}
